# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Recos' do

  use_frameworks!

  pod "SwiftyJSON"
  pod 'GDPerformanceView-Swift', '~> 2.1.1' 


end
